package edu.mephi.java.three;

public enum ESprite
{
	EMPTY,		EMPTY_SELECTED,		EMPTY_PICKED,
	SPARK,		SPARK_SELECTED,		SPARK_PICKED,
	
	APPLE,		APPLE_SELECTED,		APPLE_PICKED,
	ORANGE,		ORANGE_SELECTED,	ORANGE_PICKED,
	BANANA,		BANANA_SELECTED,	BANANA_PICKED,
	CUCUMBER,	CUCUMBER_SELECTED,	CUCUMBER_PICKED,
	WATER,		WATER_SELECTED,		WATER_PICKED,
	MEAT,		MEAT_SELECTED,		MEAT_PICKED,
	
	BOMB,		BOMB_SELECTED,		BOMB_PICKED,
	BOMB_HOT,	BOMB_HOT_SELECTED,	BOMB_HOT_PICKED,
	FIRE,		FIRE_SELECTED,		FIRE_PICKED,
	
	WALL,		WALL_SELECTED,		WALL_PICKED
}
